name: Continious Integration

on:
  push:
    branches:
      - fix/workflows
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

  test:
    name: Run Tests & Generate Coverage
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Turborepo Tests
        run: npm run test

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: packages/**/coverage/coverage-final.json

  codecov:
    name: Upload Coverage to Codecov
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        package:
          - pronotron-io
          - pronotron-pointer
          - pronotron-utils
          # add more packages here
    steps:
      - name: Download Coverage Artifact
        uses: actions/download-artifact@v5
        with:
          name: coverage-reports

      - name: Debug directory
        run: ls -R