name: Continuous Integration

on:
  push:
    branches: [ main, fix/workflows ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    name: Run Tests & Generate Coverage
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Turborepo Tests
        run: npm run test

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          # actions/upload-artifact glob pattern removes 'packages' root, see 'coverage-reports' below
          path: ./packages/**/coverage/coverage-final.json

  codecov:
    name: Upload Coverage to Codecov
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        package:
          - pronotron-io
          - pronotron-pointer
          - pronotron-utils
          # add more packages here
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Coverage Artifact
        uses: actions/download-artifact@v5
        with:
          name: coverage-reports
          # For Codecov to operate correctly, all file paths in the coverage report must match the git file structure.
          # path: packages

      - name: Debug directory
        run: ls -R

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ${{ matrix.package }}/coverage/coverage-final.json
          flags: ${{ matrix.package }}
          name: ${{ matrix.package }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true